/**
 * EduFlow Permission Matrix
 * Maps each role to the actions they are allowed to perform.
 * Import this in ProtectedRoute (frontend) and requirePermission middleware (backend).
 */
export const PERMISSIONS = {
  superadmin: [
    'governance.view',
    'governance.approve',
    'institution.settings',
    'institution.deactivate',
    'audit.view',
    'users.manage',
    'users.provision',
    'analytics.view',
  ],
  admin: [
    'attendance.view',
    'attendance.report',
    'quiz.view',
    'quiz.create',
    'quiz.grade',
    'quiz.publish',
    'gradebook.view',
    'announcements.create',
    'announcements.view',
    'institution.settings',
    'users.manage',
    'users.provision',
    'audit.view',
    'analytics.view',
    'substitution.approve',
    'substitution.manage',
    'academics.manage',
    'faculty.manage',
    'students.manage',
    'support.manage',
    'reports.export',
  ],
  faculty: [
    'attendance.mark',
    'attendance.view',
    'attendance.report',
    'quiz.create',
    'quiz.view',
    'quiz.grade',
    'quiz.publish',
    'gradebook.view',
    'announcements.view',
    'substitution.request',
    'support.create',
    'students.viewRoster',
    'academics.view',
  ],
  student: [
    'attendance.view',
    'quiz.take',
    'quiz.viewOwn',
    'gradebook.viewOwn',
    'announcements.view',
    'support.create',
    'timetable.view',
    'academics.view',
  ],
};
